version: 0.2

phases:

  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/0.12.0/terraform_0.12.0_linux_amd64.zip"           
      - "unzip terraform_0.12.0_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo terraform $TF_COMMAND completed on `date`